services:
  jlpe:
    image: vyxan/jlpe_image:3.13
    ports:
      - "8888:8888"
    volumes:
      - .:/app/enefit
      - ../jl_settings:/root/.jupyter
      - ../jl_ipython:/root/.ipython
    working_dir: /app/enefit

    environment:
      DATABASE_URL: postgresql://enefit:enefit_pass@db:5432/enefit_db
      
    entrypoint: >
      poetry run jupyter lab
      --allow-root
      --no-browser
      --ip=0.0.0.0
      --port=8888
      --IdentityProvider.token=""
      --ServerApp.disable_check_xsrf=True

    stdin_open: true
    tty: true

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  
  db:
    image: postgres:17
    profiles: ["db"]
    command: >
      postgres
      -c shared_buffers=64MB
      -c work_mem=4MB
      -c maintenance_work_mem=32MB

    environment:
      POSTGRES_USER: enefit
      POSTGRES_PASSWORD: enefit_pass
      POSTGRES_DB: enefit_db

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U enefit -d enefit_db"]
      interval: 5s
      retries: 5

volumes:
  pgdata:
